version: "3.8"

services:
  client:
    build: client/
    ports:
      - 4200:80
    networks:
      - public
      
  server:
    build: server/
    ports:
      - 3000:3000
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - JWT_SECRET=
    networks:
      - public
      
networks:
  public:
    driver: bridge