name: Build Test Run Analyze Containerize Push

on:
  push:
    branches: 
      - main
      # main (replace with main to activate pipeline)
    paths-ignore:
      - '**/README.md'
jobs:
  
  build-run-frontend:
       if: ${{github.repository == 'jaumoso/gamedb'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd frontend
            yarn install
         - name: build
           run: |
            cd frontend
            yarn build
         #- name: test
         # run: |
         #  cd frontend
         #  yarn test --no-watch --code-coverage
         #- name: Upload coverage report
         #  uses: actions/upload-artifact@master
         #  with:
         #     name: coveragefrontend
         #     path: frontend/coverage/

  build-run-backend:
       needs: build-run-frontend
       if: ${{github.repository == 'jaumoso/gamedb'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd backend
            yarn install
         - name: build
           run: |
            cd backend
            yarn build
         #- name: test
         #  run: |
         #   cd backend
         #   yarn test --watch=false --coverage
         #- name: Upload coverage report
         #  uses: actions/upload-artifact@master
         #  with:
         #     name: coveragebackend
         #     path: backend/coverage/
            
  sonar-frontend:
    needs: build-run-backend
    name: Sonar Analyze ANGULAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Download coverage report
      #  uses: actions/download-artifact@master
      #  with:
      #    name: coveragefrontend
      #    path: frontend/coverage/
      - name: go to folder
        run: |
          cd frontend
          pwd
          ls
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # Additional arguments to the sonarcloud scanner
          args: 
            -Dsonar.projectKey=jaumoso_gamedb_frontend
            -Dsonar.organization=jaumoso
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: frontend/.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  sonar-backend:
    needs: sonar-frontend
    name: Sonar Analyze NESTJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Download coverage report
      #  uses: actions/download-artifact@master
      #  with:
      #    name: coveragebackend
      #    path: backend/coverage/
      - name: go to folder
        run: |
          cd backend
          pwd
          ls
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # Additional arguments to the sonarcloud scanner
          args: 
            -Dsonar.projectKey=jaumoso_gamedb_backend
            -Dsonar.organization=jaumoso
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: backend/.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}

  # build-docker-images-and-publish:
  #   needs: sonar-backend
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Docker Login
  #     uses: docker/login-action@v1
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #   - name: Build and Publish Docker FRONTEND
  #     id: docker_build_frontend
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: frontend/.
  #       push: true
  #       tags: |
  #         ghcr.io/jaumoso/gamedb/gamedb-frontend:${{ github.sha }}
  #   - name: Build and Publish Docker BACKEND
  #     id: docker_build_backend
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: backend/.
  #       push: true
  #       tags: |
  #         ghcr.io/jaumoso/gamedb/gamedb-backend:${{ github.sha }}
  #   - name: Print Image Digests
  #     run: |
  #       echo ${{ steps.docker_build_frontend.outputs.digests }}
  #       echo ${{ steps.docker_build_backend.outputs.digests }}